name: is-conf-man
version: git
summary: OfflineIMAP
description: |
  OfflineIMAP is software that downloads your email mailbox(es) as local
  Maildirs. OfflineIMAP will synchronize both sides via IMAP.
confinement: devmode
base: core18

parts:
  test-offlineimap-is-conf-man:
    plugin: python
    python-version: python3
    source: .
    stage-packages:
      - python-six

apps:
  is-conf-man:
    command: bin/is_conf_man
